# This is a basic workflow to help you get started with Actions

name: Generate VcRedist report 

# Controls when the action will run. 
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Change back to Ubuntu once we fix the script
    #runs-on: ubuntu-latest
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run PowerShell commands
      - name: Install and run tests
        shell: pwsh
        run: |
          . .\ci\Install.ps1
          . .\ci\Build.ps1
          . .\ci\Tests.ps1
